language: node_js
node_js:
  - "node"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install -y libc6:i386 libstdc++6:i386
install:
  - npm install
script:
  - npm run lint
  - npm run build
  - npm run dist
  - ./dist/edison-central-linux &
  - sleep 3
  - npm test
